### PR TITLE
BBL tweaks for clarity and easier programming

### LINKED ISSUE #6: SLA data set shouldn't use spaces in column names
It's not the end of the world, but it makes it easier if no spaces.

### PR DESCRIPTION
**Pull request by bpbond**
Closes #6

### CODE REVIEW

**Comment by bpbond** [comment]
Note that I opened an issue to identify a problem – see #6 – and this PR, if merged, will automatically close it.

**Comment by bpbond** [comment]
P.S. This PR is **not ready for merging**. There's a problem, and I should be asked to change something.

**Review by lilliehaddock — CHANGES_REQUESTED** [review]
Looks like you misspelled "modified" on line 3! Whoops

**Comment by bpbond** [comment]
@lilliehaddock @hmoore28 @marideeweber Here's what happens when there's a "conflict", i.e. it can't figure out what to do with two separate sets of changes. Let's take a look at this together.

**Comment by bpbond** [comment]
This is out of date–closing.

**Pull request closed without merging**
